-- Adds group messaging tables backing lua/src/routes.lua's M.list_groups/
-- M.create_group/M.group_messages/M.send_group_message (2026-08-09).
--
-- The React frontend (MessagesPage.jsx) has always had a complete "New
-- group" UI calling GET/POST /api/threads and GET/POST
-- /api/threads/:id/messages, but none of it existed server-side -- not even
-- in the original Python backend. This is genuinely new schema, unlike most
-- prior migrations in this project which recovered an existing Python
-- table shape.
--
-- Idempotent: safe to re-run.

CREATE TABLE IF NOT EXISTS message_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120),
  created_by BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS message_group_members (
  group_id BIGINT NOT NULL REFERENCES message_groups(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  joined_at TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY (group_id, user_id)
);

CREATE TABLE IF NOT EXISTS group_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL REFERENCES message_groups(id) ON DELETE CASCADE,
  sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  body VARCHAR(2000) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_group_messages_group ON group_messages(group_id, created_at);
CREATE INDEX IF NOT EXISTS idx_group_members_user ON message_group_members(user_id);
