-- Adds background_music, backing the admin-managed shuffled ambient
-- soundtrack feature (2026-08-22): up to 10 tracks the site owner can
-- inject/remove from the admin panel, which every visitor hears shuffled
-- while browsing, ducking out when a video with sound starts playing.
--
-- Stored as a DB blob (BYTEA), same convention as media_items' DB-blob
-- storage -- there are at most 10 of these and they're small (audio, not
-- video), so no on-disk fallback path is needed the way media_files.lua
-- has one for legacy pre-migration uploads.
--
-- Idempotent: safe to re-run.

CREATE TABLE IF NOT EXISTS background_music (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  original_filename TEXT NOT NULL,
  mime_type TEXT NOT NULL,
  content BYTEA NOT NULL,
  file_size BIGINT NOT NULL,
  sort_order BIGINT NOT NULL DEFAULT 0,
  uploaded_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_background_music_sort ON background_music(sort_order, id);
