-- Image Gallery: normalize every numeric(20,0) column (produced mechanically by
-- the original MariaDB `bigint unsigned` -> Postgres conversion) to bigint.
--
-- Why: all PK/identity columns in this schema are already `bigint` (see
-- `generated by default as identity`), so numeric(20,0) FK/id columns can't
-- form a foreign key against them (Postgres error: "incompatible types:
-- numeric and bigint"). None of the actual values in this domain (internal
-- auto-increment ids, view/download counters, file sizes up to the 3GiB
-- upload cap, image pixel dimensions) ever approach bigint's signed range
-- (+-9.2e18), so there is no real loss versus the unsigned range numeric(20,0)
-- was preserving in theory. This also means the Lua rewrite's Postgres layer
-- needs no new NUMERIC (oid 1700) deserializer patch for this database --
-- pg.lua's existing bigint (oid 20) string-deserialization fix already covers
-- every wide-integer column here as-is.
--
-- Safe to run only while these tables are empty (verified 2026-07-26: every
-- table but `categories`/`site_settings` has 0 rows). If re-run later against
-- a populated table, do this BEFORE the FK/unique fixups in
-- pg_schema_fixups.sql, and double check no value actually exceeds bigint's
-- range first.

BEGIN;

ALTER TABLE ai_media_learning_state
  ALTER COLUMN media_id TYPE bigint USING media_id::bigint,
  ALTER COLUMN user_id TYPE bigint USING user_id::bigint;

ALTER TABLE ai_vision_training_examples
  ALTER COLUMN user_id TYPE bigint USING user_id::bigint,
  ALTER COLUMN media_id TYPE bigint USING media_id::bigint;

ALTER TABLE categories
  ALTER COLUMN created_by TYPE bigint USING created_by::bigint;

ALTER TABLE friend_requests
  ALTER COLUMN requester_id TYPE bigint USING requester_id::bigint,
  ALTER COLUMN addressee_id TYPE bigint USING addressee_id::bigint;

ALTER TABLE media_bookmarks
  ALTER COLUMN user_id TYPE bigint USING user_id::bigint,
  ALTER COLUMN media_id TYPE bigint USING media_id::bigint;

ALTER TABLE media_collection_items
  ALTER COLUMN collection_id TYPE bigint USING collection_id::bigint,
  ALTER COLUMN media_id TYPE bigint USING media_id::bigint;

ALTER TABLE media_collections
  ALTER COLUMN user_id TYPE bigint USING user_id::bigint;

ALTER TABLE media_comments
  ALTER COLUMN media_id TYPE bigint USING media_id::bigint,
  ALTER COLUMN user_id TYPE bigint USING user_id::bigint,
  ALTER COLUMN parent_comment_id TYPE bigint USING parent_comment_id::bigint;

ALTER TABLE media_file_chunks
  ALTER COLUMN file_id TYPE bigint USING file_id::bigint;

ALTER TABLE media_files
  ALTER COLUMN file_size TYPE bigint USING file_size::bigint,
  ALTER COLUMN created_by TYPE bigint USING created_by::bigint;

ALTER TABLE media_item_subcategories
  ALTER COLUMN media_id TYPE bigint USING media_id::bigint,
  ALTER COLUMN subcategory_id TYPE bigint USING subcategory_id::bigint;

ALTER TABLE media_items
  ALTER COLUMN user_id TYPE bigint USING user_id::bigint,
  ALTER COLUMN category_id TYPE bigint USING category_id::bigint,
  ALTER COLUMN file_size TYPE bigint USING file_size::bigint,
  ALTER COLUMN views TYPE bigint USING views::bigint,
  ALTER COLUMN downloads TYPE bigint USING downloads::bigint,
  ALTER COLUMN media_file_id TYPE bigint USING media_file_id::bigint,
  ALTER COLUMN subcategory_id TYPE bigint USING subcategory_id::bigint;

ALTER TABLE media_likes
  ALTER COLUMN user_id TYPE bigint USING user_id::bigint,
  ALTER COLUMN media_id TYPE bigint USING media_id::bigint;

ALTER TABLE media_reactions
  ALTER COLUMN media_id TYPE bigint USING media_id::bigint,
  ALTER COLUMN user_id TYPE bigint USING user_id::bigint;

ALTER TABLE media_reports
  ALTER COLUMN media_id TYPE bigint USING media_id::bigint,
  ALTER COLUMN user_id TYPE bigint USING user_id::bigint;

ALTER TABLE message_thread_members
  ALTER COLUMN thread_id TYPE bigint USING thread_id::bigint,
  ALTER COLUMN user_id TYPE bigint USING user_id::bigint;

ALTER TABLE message_threads
  ALTER COLUMN created_by TYPE bigint USING created_by::bigint;

ALTER TABLE moderation_audit_log
  ALTER COLUMN actor_id TYPE bigint USING actor_id::bigint,
  ALTER COLUMN target_id TYPE bigint USING target_id::bigint;

ALTER TABLE notifications
  ALTER COLUMN recipient_id TYPE bigint USING recipient_id::bigint,
  ALTER COLUMN actor_id TYPE bigint USING actor_id::bigint,
  ALTER COLUMN media_id TYPE bigint USING media_id::bigint;

ALTER TABLE saved_searches
  ALTER COLUMN user_id TYPE bigint USING user_id::bigint;

ALTER TABLE site_settings
  ALTER COLUMN updated_by TYPE bigint USING updated_by::bigint;

ALTER TABLE subcategories
  ALTER COLUMN category_id TYPE bigint USING category_id::bigint,
  ALTER COLUMN created_by TYPE bigint USING created_by::bigint;

ALTER TABLE thread_messages
  ALTER COLUMN thread_id TYPE bigint USING thread_id::bigint,
  ALTER COLUMN sender_id TYPE bigint USING sender_id::bigint;

ALTER TABLE user_avatar_files
  ALTER COLUMN user_id TYPE bigint USING user_id::bigint,
  ALTER COLUMN file_size TYPE bigint USING file_size::bigint;

ALTER TABLE user_blocks
  ALTER COLUMN blocker_id TYPE bigint USING blocker_id::bigint,
  ALTER COLUMN blocked_id TYPE bigint USING blocked_id::bigint;

ALTER TABLE user_follows
  ALTER COLUMN follower_id TYPE bigint USING follower_id::bigint,
  ALTER COLUMN followed_id TYPE bigint USING followed_id::bigint;

ALTER TABLE user_messages
  ALTER COLUMN sender_id TYPE bigint USING sender_id::bigint,
  ALTER COLUMN recipient_id TYPE bigint USING recipient_id::bigint;

ALTER TABLE users
  ALTER COLUMN avatar_file_id TYPE bigint USING avatar_file_id::bigint,
  ALTER COLUMN banned_by TYPE bigint USING banned_by::bigint;

COMMIT;
